[package]
name = "using-bindgen"
version = "0.1.0"
authors = ["Mikael Silvén <mikael@silven.nu>"]
build = "build.rs"

[build-dependencies]
bindgen = "0.26"
cbindgen = "0.4"

[lib]
crate-type = ["cdylib"]
